### PR TITLE
Make lib/Page/*.Page.php compatible with PHP 8.2

### PR DESCRIPTION
**Pull request by TDannhauer**
PHP8.2 requires compatible interfaces between base class and extended classes. This PR unifies the interfaces

### CODE REVIEW

**Comment by TDannhauer** [comment]
added also changes for getPermissions()

**Comment by szepeviktor** [comment]
@yunosh Could you take a look at this PR?

**Comment by TDannhauer** [comment]
Any news or reviews?

**Comment by mrubinsk** [comment]
Merged, thanks!

**Pull request merged**
